CREATE OR REPLACE FUNCTION IS_GROUP_MEMBER(GM_GROUP_ID IN NUMBER, GM_USER_ID IN NUMBER)
RETURN VARCHAR2 IS
    RET VARCHAR2(50);
    CNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO CNT FROM GROUP_MEMBERS
    WHERE USER_ID = GM_USER_ID AND GROUP_ID= GM_GROUP_ID;
    IF CNT = 0 THEN
        RET := 'NO';
    ELSE
        RET := 'YES';
    end if;
    RETURN RET;
end;


CREATE OR REPLACE FUNCTION IS_PENDING_MEMBER(PM_GROUP_ID IN NUMBER, PM_USER_ID IN NUMBER)
RETURN VARCHAR2 IS
    RET VARCHAR2(50);
    CNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO CNT FROM PENDING_MEMBERS
    WHERE USER_ID = PM_USER_ID AND GROUP_ID= PM_GROUP_ID;
    IF CNT = 0 THEN
        RET := 'NO';
    ELSE
        RET := 'YES';
    end if;
    RETURN RET;
end;


CREATE OR REPLACE FUNCTION IS_LIKED(L_POST_ID IN NUMBER, L_USER_ID IN NUMBER)
RETURN VARCHAR2 IS
    RET VARCHAR2(50);
    CNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO CNT FROM LIKES
    WHERE USER_ID = L_USER_ID AND POST_ID= L_POST_ID;
    IF CNT = 0 THEN
        RET := 'NO';
    ELSE
        RET := 'YES';
    end if;
    RETURN RET;
end;

CREATE OR REPLACE FUNCTION IS_NEARBY(LATITUDE1 IN NUMBER, LONGITUDE1 IN NUMBER, LATITUDE2 IN NUMBER, LONGITUDE2 IN NUMBER)
RETURN VARCHAR2 IS
BEGIN
    IF LATITUDE2 is null OR LONGITUDE2 is null THEN
        RETURN 'YES';
    ELSIF LATITUDE1 is null OR LONGITUDE1 is null THEN
        RETURN 'NO';
    ELSIF SQRT(POWER(LATITUDE1-LATITUDE2, 2) + POWER(LONGITUDE1-LONGITUDE2, 2)) <=0.05 THEN
        RETURN 'YES';
    ELSE RETURN 'NO';
    end if;
end;


CREATE OR REPLACE FUNCTION IS_GOING(EP_EVENT_ID IN NUMBER, EP_USER_ID IN NUMBER)
RETURN VARCHAR2 IS
    RET VARCHAR2(50);
    CNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO CNT FROM EVENT_PARTICIPANTS
    WHERE USER_ID = EP_USER_ID AND EVENT_ID = EP_EVENT_ID;
    IF CNT = 0 THEN
        RET := 'NO';
    ELSE
        RET := 'YES';
    end if;
    RETURN RET;
end;