CREATE SEQUENCE USER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SKILL_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE RESEARCH_INTEREST_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INTEREST_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE EDUCATION_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE WORK_EXPERIENCE_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ACHIEVEMENT_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE PUBLICATION_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE GROUP_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE GROUP_MEMBER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE PENDING_MEMBER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE POST_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE COMMENT_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE LIKE_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE EVENT_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SCHEDULE_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE NOTIFICATION_SEQ
START WITH 1
INCREMENT BY 1;